### ISSUE TITLE
Question - Best approach bridging Spring RestComponent

### ISSUE THREAD

**Issue by flaviocordova** [moleculer-java/moleculer-java-web#2]
Hi @berkesa, I've been using Moleculer Java for a while but mostly serving services and now I have to consume some other (moleculer) services more often and thus I need to be more concerned about if I'm doing it the best way.

My first question is how is the best way to call a service from a @RequestMethod. So far I've being doing something like this:

```
@RequestMapping(value = "/search", method = RequestMethod.POST)
@ResponseBody
public List<Map<String, Object>> findAccount(@RequestBody Map<String, Object> params) throws Exception {
	var result = (List<Map<String, Object>>) serviceBroker.call("accounts.findByEmail", params)
			.waitFor()
			.asObject();
	return result;
}
```

But I'm quite sure that's not the best way specially for the ```waitFor()``` that blocks the thread. I did a fast research of how spring implements async requests but I couldn't connect the dots.

The second question goes a step further: Is there a way to incorporate API Gateway as a spring filter, so I could delegate some requests to it but keep all other requests being processed by @RestComponents I already have? Also in this case, would I be able to I inject a meta.user info based on the current (java.security.)Principal?

**Comment by berkesa** [comment]
Hi!
Yes, the ApiGateway is truly a non-blocking implementation (based on performance / high-load tests, the ApiGateway REST faster than Spring REST). If I understand correctly, do you like to use Spring's web server and ApiGateway Servlet in the same application?

**Comment by berkesa** [comment]
Hi!
A non-blocking solution may be possible with Spring async services. The sketch of the REST service should be something like this (_CompletableFuture_ response and _Async_ annotation are important):

```java
	@Async
	public CompletableFuture<Object> findAccount(...) throws Exception {
		
		// Create "empty" response container
		CompletableFuture<Object> future = new CompletableFuture<>();
		
		broker.call("...").then(rsp -> {
			future.complete(rsp.asObject()); // Complete later normally
		}).catchError(err -> {
			future.completeExceptionally(err); // Complete later with error
		});
		
		// Return uncompleted future
		return future;
	}
```

**Comment by flaviocordova** [comment]
Yes...
I can't afford rewriting all current rest services (implemented as @RestControllers) to Moleculer but I need to "proxy " remote services (from other apps)... I could do it creating new @RequestMapping methods and calling the services (as shown in question 1) or maybe I could use API Gateway as a spring filter to process some requests (keeping the rest as they are now).

**Comment by flaviocordova** [comment]
> Hi!
> A non-blocking solution may be possible with Spring async services. The sketch of the REST service should be something like this (_CompletableFuture_ response and _Async_ annotation are important):
> 
> ```java
> 	@Async
> 	public CompletableFuture<Object> findAccount(...) throws Exception {
> 		
> 		// Create "empty" response container
> 		CompletableFuture<Object> future = new CompletableFuture<>();
> 		
> 		broker.call("...").then(rsp -> {
> 			future.complete(rsp.asObject()); // Complete later normally
> 		}).catchError(err -> {
> 			future.completeExceptionally(err); // Complete later with error
> 		});
> 		
> 		// Return uncompleted future
> 		return future;
> 	}
> ```

It seems to answer question 1.. :)
I'll try it soon!

**Comment by berkesa** [comment]
Did you succeed? Can I close this issue?

**Comment by flaviocordova** [comment]
yes, it did work !!!
But the second questions still remains...

Is there any way to use API Gateway as a filter in spring-boot web request chain?

Something like:

```
@Component
public class StaticFilesFilter extends GenericFilterBean {

        @Autowired
	private ApiGateway gateway;
	
	@Override
	public void doFilter(ServletRequest request, ServletResponse response, FilterChain filterChain) throws IOException, ServletException {
		HttpServletRequest req = (HttpServletRequest) request;
                HttpServletResponse res = (HttpServletResponse) response;

               if(!req.getRequestURI().startsWith('/mol/') {
    			filterChain.doFilter(request, response);
               } else {
                      this.gateway.processRequest(request, response);
               }
	}
}
```

**Comment by berkesa** [comment]
Yes, perhaps possible, as follows:
A custom class must be derived from the **services.moleculer.web.servlet.MoleculerServlet** ApiGateway class.
Then you have to rewrite the **constructor** and **init** method, something like this:

```java
public EmbeddableMoleculerServlet extends MoleculerServlet {

public EmbeddableMoleculerServlet(ServiceBroker broker, ApiGateway gateway) {
	this.broker  = broker;
	this.gateway = gateway;
}

@Override
public void init(ServletConfig config) throws ServletException {

	// Don't call super.init(config)
	webSocketRegistry = new ServletWebSocketRegistry(config, broker, 15);
	gateway.setWebSocketRegistry(webSocketRegistry);

	// You can try "AsyncService" later instead of "BlockingService"
	serviceMode = new BlockingService(broker, gateway, 3 * 60 * 1000);
}

}
```

...and in your GenericFilterBean:

```java
@Autowired
private ServiceBroker broker;

@Autowired
private ApiGateway gateway;

// This part comes into a Spring initializer function,
// after the above variables (broker and gateway) have been set:
EmbeddableMoleculerServlet embeddedServlet = new EmbeddableMoleculerServlet(broker, gateway);

@Override
public void doFilter(ServletRequest request, ServletResponse response, FilterChain filterChain)
    throws IOException, ServletException {
	if(req.getRequestURI().startsWith('/mol/') {

		// Invoke the ApiGateway then the ServiceBroker via "MoleculerServlet"
		embeddedServlet.service(request, response);

	} else {
		filterChain.doFilter(request, response);
	}
}
```
I haven’t tried the above, but it should work in principle.

**Comment by flaviocordova** [comment]
Hi @berkesa 

I'm testing a way to bridge spring as you recommended but I'm having some problems I think you may help me.. 😄 

Since I'm not working with websockets I decided to skip the servlet and work directly in the Filter, creating a Blocking/AsyncService to forward the request to api gateway, like this:

```java
package br.com.hunterco.commander.config;

import java.io.IOException;

import javax.servlet.FilterChain;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.GenericFilterBean;

import services.moleculer.ServiceBroker;
import services.moleculer.web.ApiGateway;
import services.moleculer.web.servlet.service.AsyncService;
import services.moleculer.web.servlet.service.BlockingService;

@Component
public class ApiGatewayFilter extends GenericFilterBean {
	@Autowired
	private ApiGateway gateway;
	@Autowired
	private ServiceBroker broker;
	
	private BlockingService serviceRunner;
	
	@Override
	protected void initFilterBean() throws ServletException {
		super.initFilterBean();
		this.serviceRunner = new BlockingService(this.broker, this.gateway, 15000);
	}
	
	@Override
	public void doFilter(ServletRequest request, ServletResponse response, FilterChain filterChain) throws IOException, ServletException {
		HttpServletRequest req = (HttpServletRequest) request;
        	HttpServletResponse res = (HttpServletResponse) response;
        
        	System.out.println("Requesting " + req.getRequestURI()); // shows /mol/accounts/config
        
	    	if (!req.getRequestURI().startsWith("/mol/")) {
    			filterChain.doFilter(request, response);
    			return;
    		}
	        try {
			System.out.println("Here we go!");
			this.serviceRunner.service(req, res);
		} catch (Exception e) {
			System.out.println("=========== EXCEPTION IN API GATEWAY ==============");
			e.printStackTrace();
			throw new ServletException("API GATEWAY ERROR", e); 
		}
	}
}
```

However, I'm getting a NullPointerException here:
```
java.lang.NullPointerException
at services.moleculer.web.router.Route.findMapping(Route.java:104)
at services.moleculer.web.ApiGateway.service(ApiGateway.java:484)
at services.moleculer.web.servlet.service.BlockingService.service(BlockingService.java:62)
...
```

It happens because Route.findMapping is called with a null ```path``` argument. By the name of the method, I guess it should receive the path I have requested, in this case, /mol/accounts/config..

Digging a little bit I discovered the path is null because AbstractWebRequest implemented getPath this way:

```java
	@Override
	public String getPath() {
		return req.getPathInfo();
	}
```

Indeed, the request I receive in the filter has a null getPathInfo and while the path is retrieved using getRequestURI() and it looks like there's some differences of how Spring and Netty deal with the request:  https://stackoverflow.com/questions/8078364/spring-mvc-controller-getpathinfo-is-null

So, what do you think?
I'd be glad to hear I just made a mistake..

**Comment by berkesa** [comment]
Do you think that if I rewrite the `getPath()` function like this, it would work with Spring MVC as well?

```java
	// In "AbstractWebRequest":

	@Override
	public String getPath() {
		String path = req.getPathInfo();
		if (path == null) {
			return req.getRequestURI();
		}
		return path;
	}
```

**Comment by berkesa** [comment]
Someone is using code like this for the same purpose:
```java
String path = request.getRequestURI().substring(request.getContextPath().length());
```
Which one could be better?

**Comment by berkesa** [comment]
Hi!
I modified the `getPath()` function. I tried with a Filter, it worked for me (before that I also got a NullPointerException). Try downloading `moleculer-java-web` version **1.2.9**:

```xml
<!-- https://mvnrepository.com/artifact/com.github.berkesa/moleculer-java-web -->
<dependency>
	<groupId>com.github.berkesa</groupId>
	<artifactId>moleculer-java-web</artifactId>
	<version>1.2.9</version>
</dependency>
```
Thanks again for your feedback. Write if there is anything else ...

**Comment by flaviocordova** [comment]
Hi @berkesa , it did work indeed...

my final step is to be able transport the information in the Principal (javax.security.Principal) to the context (meta.user).

My first (and only, so far) is creating a middleware and attach it to the route, but I'm not sure how I could inject meta.user to the request, so the service could receive this information..

I expected to be able to inject it somehow in WebRequest but it doesn't seem to have any suitable method to change meta properties... I also tried setting the config argument  ```RequestProcessor install(RequestProcessor next, Tree config)``` but it didn't work either... the next argument also doesn't have any method to set the meta.

I thought I could take a look how BasicAuthenticator works but I actually got more confused... it calls 
```
// Store username in properties
rsp.setProperty(PROPERTY_USER, username);
```

but it's called in the response, doesn't make much sense.. I tried, anyway, and it didn't work..

So I'm a little lost.. how can I inject meta information to the call ?

PS.: should it be another issue?

**Comment by berkesa** [comment]
Hi, please check out the code snippet below (the `setBeforeCal` block) to see if this is what you are looking for:

https://github.com/moleculer-java/moleculer-spring-boot-demo/blob/master/src/main/java/my/application/MoleculerApplication.java#L216

In this section, the request object (which can be casted to `HttpServletRequest` by the `getInternalObject` method) and the Tree/JSON object named `data` are available before the call. You can extract data from the request and **put it in the Tree's "meta" block**. The `meta` block goes through the molecular call chain. Because of this, not only Java but also Node.js `Services` see its content.

More samples about this feature: https://moleculer-java.github.io/site/moleculer-web.html#route-hooks

**Comment by flaviocordova** [comment]
Hi @berkesa, I really didn't figure I could use hooks, sorry..

Anyway, it didn't work.. 😞 
I'm not sure but the principal is being lost somewhere between the middleware and the hook..

Look the logs I printed:

```
FILTER REQUEST INSTANCE: SecurityContextHolderAwareRequestWrapper[ org.springframework.security.web.header.HeaderWriterFilter$HeaderWriterRequest@538a3c33]
FILTER PRINCIPAL.......: org.springframework.security.authentication.UsernamePasswordAuthenticationToken@96b5333e: Principal: br.com.hunterco.commander.auth.CommanderPrincipal@694accfa; Credentials: [PROTECTED]; Authenticated: true; Details: null; Not granted any authorities

MIDDLEWARE REQUEST INSTANCE: SecurityContextHolderAwareRequestWrapper[ org.springframework.security.web.header.HeaderWriterFilter$HeaderWriterRequest@538a3c33]
MIDDLEWARE PRINCIPAL.......: org.springframework.security.authentication.UsernamePasswordAuthenticationToken@96b5333e: Principal: br.com.hunterco.commander.auth.CommanderPrincipal@694accfa; Credentials: [PROTECTED]; Authenticated: true; Details: null; Not granted any authorities

HOOK REQUEST INSTANCE: SecurityContextHolderAwareRequestWrapper[ org.springframework.security.web.header.HeaderWriterFilter$HeaderWriterRequest@538a3c33]
HOOK PRINCIPAL.......: null
``` 

Notice that the request instance seems to be the same in all 3 points, but principal is null when it gets to the hook... 🤷‍♂️ 

Do you have any idea what could be happening ?

**Comment by berkesa** [comment]
Hi @flaviocordova!

Probably (it's very likely) one of the internal components (Spring Security API, etc.) use a **`java.lang.ThreadLocal`**. Many APIs use this. For example Hibernate stores the database session in a `ThreadLocale` by default. Spring stores the state of `@Transactional` objects/variables in a similar way. When such a variable is processed using an Executor or a Thread Pool, it loses its value (because the parent `Thread` changes).

**The solution may be to store the Principal object in a variable before it becomes `null`.**
This variable should **not** be a `ThreadLocal`, but an ordinary variable (or Map or a custom attribute of the Request/Response).
It will be possible to reach this variable from the `setBeforeCal` hook.

By the way, in what kind of Middleware is Principal still available? Is it an HTTP Middleware?

**Service Middleware**
https://moleculer-java.github.io/site/middlewares.html#about-middlewares

**HTTP Middleware**
https://moleculer-java.github.io/site/moleculer-web.html#http-middlewares

**Comment by flaviocordova** [comment]
Hi @berkesa 

You're probably right.. It makes a lot of sense that spring keeps request-scoped info in threadlocal variables...

I understand you suggestion but is looks like a big workaround, full of potential for leaking, for something that should be out-of-the-box, don't you think? It's very likely that anyone using moleculer-web will have to deal with authentication and authorization.

Let's compare to how nodejs version deals with this. We set the route as authenticated and implement an authorization method (same for authorization). Maybe the java version could replicate the same structure, don't you think?

You could define an interface (AuthenticationProvider) and set it to the route, somethink like this:


```
public class MyCustomAuthenticator implements AuthenticationProvier {
     public authorize(Context ctx, Route route, WebRequest req, WebResponse res) {
        // do your stuff here, set context meta if needed
     }
}

....

Route r = new Route();
r.setAuthenticationProvider(new MyCustomAuthenticator())

```

This way I think the engine itself would know better how to manage threads and contexts. That could avoid breaking changes in the future if the inner logic (and threads and so on) changes.

What do you think? 🙂

**Comment by flaviocordova** [comment]
By the way, I was using HttpMiddleware.. I don't think ServiceMiddleware would have access to the request to get the principal, would it?

**Comment by berkesa** [comment]
Perhaps the quick fix is to extract the `Principal` object in a `HttpMiddleware` and then put it into one of the attributes of `WebResponse` (eg. `rsp.setProperty("principal", p)`).

Later, the `setBeforeCall` hook can extract the `Principal` from the `WebResponse` by using the `rsp.getProperty("principal")` function.

Finally, any variable from the `Principal` can be inserted into the `meta` block of the `data` structure (this can be done in the same `setBeforeCall` function).

**Comment by berkesa** [comment]
I can't answer the previous question / suggestion. I need more time to deal with this. But it would be possible to create a structure similar to the one in the Node.js version (most of the WebMiddleware also came from the Node.js version or from the Express.js).

**Comment by berkesa** [comment]
In the above solution, imho there is no possibility of leaking; WebResponse is only a short-lived object, not reused or cached, its content does not remain after a call.

**Comment by flaviocordova** [comment]
Hi @berkesa 

It did work and I agree, setting a property was I good way to avoid memory leaks and make it less error prone..
I appreciate all you help, thanks once again...

But my suggestion still remains and I hope you consider it for a future implementation. Creating both a middleware and a hook is a too tricky solution for a quite trivial problem to my taste and I think there's room for improvement...
