### ISSUE TITLE
Query parameters are not forwarded

### ISSUE THREAD

**Issue by flaviocordova** [moleculer-java/moleculer-java-web#4]
ApiGateway is not adding values received as query parameters to the requested service...

For example, I have this route definition:
```java
route.addAlias("GET", "ckt/getCompany/:id", "companies.getByExternalId");
```

This service may accept an optional parameter called populateAccounts(boolean)...

When I request it as ```/ckt/getCompany/1234?populateAccounts=true``` it should ```populate id: 1234``` and ```populateAccounts: true```, but populateAccounts is ignored and won't reach the service.

**Comment by flaviocordova** [comment]
Digging the code I found this code at ActionInvoker:

```java
		if (isStatic || indexes.length == 0) {
			// HTTP GET QueryString
			String query = req.getQuery();
			if (query != null && !query.isEmpty()) {
				parseQueryString(params, query);
			}
		} else {

			// Parameters in URL (eg "/path/:id/:name")
			String[] tokens = req.getPath().split("/");
			for (int i = 0; i < indexes.length; i++) {
				params.put(names[i], tokens[indexes[i]]);
			}
		}
```

Apparently the formats are exclusive, that is, you can use path parameters OR query parameters, not both.
Removing the if statement and processing the two codes could fix it (probably deprecating isStatic field).

**Comment by berkesa** [comment]
Hi! Upgrade "**moleculer-java-web**" to "**1.2.10**".
In this version, I changed the behavior, just like you wrote. I tested and the path-based variable pass
and the query string-based variable pass work well on a same `Action`
(eg. _/ckt/getCompany/1234?populateAccounts=true_).
